name: Keep n8n Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep n8n awake
        run: |
          for i in {1..3}; do
            curl -I https://n8n-tqqo.onrender.com && break || sleep 60
          done
