name: Keep n8n Alive - 1

on:
  schedule:
    - cron: '*/3 * * * *'  # Runs every 3 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep n8n awake
        run: curl -I https://n8n-tqqo.onrender.com || true
